services:
  # you can launch multiple servers by adding more services, with unique names
  pycraft:
    image: itzg/minecraft-server  # java edition
    # this lets you connect to the server using ssh
    
    tty: true
    stdin_open: true

    # ports enable communication between the host (left) and container (right)
    ports:
      # for game play
      - "25565:25565"
      # for FruitJuice plugin
      - "4711:4711"
      # for rcon commands -- note that this must be the same as RCON_PORT below
      - "25575:25575"

    environment:
      EULA: "TRUE"
      MEMORY: "4G"
      # installs the FruitJuice plugin
      TYPE: "PAPER"  
      # version of Minecraft-- check PaperMC/FruitJuice plugin for compatibility
      VERSION: "1.20.6"  
      # gameplay settings
      DIFFICULTY: "normal"
      MODE: "creative" # "survival"
      SERVER_NAME: "PyCraft"
      ALLOW_CHEATS: "true"
      # this gives the player admin privileges -- modify with Micraft username
      OPS: "AdminPlayerName" 

      # RCON settings
      ENABLE_RCON: "true"
      RCON_PASSWORD: "change-to-custom-password"  # change this!
      RCON_PORT: "25575"

    volumes:
      # attach the subdirectory 'data' to the container's /data path
      - ./data:/data
      # attach a plugins subdirectory to load the FruitJuice plugin
      - ./plugins:/plugins

      # get the latest FruitJuice_*.jar and it add to /plugins subdirectory
      # https://github.com/jdeast/FruitJuice/tree/master/target 
      