name: FruitJuice
description: A plugin that provides a Python SDK for the Minecraft API.
author: [Zhuowei,MinecraftDawn,jdeast,mwrowe]
version: '0.4.0b'
api-version: 1.13
main: FruitJuice.FruitJuicePlugin
database: false
startup: postworld