authors: [Zhuowei, MinecraftDawn, jdeast, d4g33z, mwrowe]
database: false
description: Implementation of the Minecraft Python API
main: fruitjuice.FruitJuicePlugin
name: FruitJuice
startup: postworld
version: '0.5.1'
api-version: '1.13'
