author: [Zhuowei,MinecraftDawn,jdeast]
database: false
description: Implementation of the Minecraft Python API
main: fruitjuice.FruitJuicePlugin
name: FruitJuice
startup: postworld
version: '0.1.0'
api-version: 1.13