# Micraft Server with FruitJuice plugin
# This file is used to set up a Minecraft server using Docker Compose.
# The FruitJuice plugin lets you connect to the server from python using
# the `pyncraft` python library.

# It expects two environment variables to be set:
# - OPS_PLAYERS: a comma-separated list of players to assign admin privileges
# - RCON_PASSWORD: the password for RCON commands
# These may be defined in a .env file in the same directory as this file, or set
# in your environment before running the docker-compose command.

# It also expects a directory named 'data' to exist in the same directory as 
# this file, and a directory named 'plugins' to exist, which will be used to
# store the FruitJuice plugin and any other plugins you want to use.

# ViaVersion lets players connect to the server from newer versions of Minecraft.
# Get the latest ViaVersion.jar and it add to /plugins subdirectory
# https://hangar.papermc.io/ViaVersion/ViaVersion

# Get the latest FruitJuice_*.jar and it add to /plugins subdirectory
# https://github.com/jdeast/FruitJuice/tree/master/target 

services:
  # you can launch multiple servers by adding more services, with unique names
  pyncraft:
    image: itzg/minecraft-server  # java edition

    # this lets you connect to the server using ssh
    tty: true
    stdin_open: true

    # ports enable communication between the host and container
    # format is host_port:container_port; container_port should not change
    ports:
      # for game play
      - "25565:25565"
      # for FruitJuice plugin
      - "4711:4711"
      # for rcon commands -- note that this must be the same as RCON_PORT below
      - "25575:25575"
      # for bedrock edition via GeyserMC
      - "19132:19132/udp"  # uncomment to enable Bedrock Edition support
      # scratch port
      - 14711:14711

    environment:
      # this must be set to "TRUE" to accept the EULA
      # see https://www.minecraft.net/en-us/eula
      EULA: "TRUE"
      # adjust this based on your host system's resources
      MEMORY: "8G"
      # installs the FruitJuice, Geyser, Floodgate and ViaVersion plugins
      TYPE: "PAPER"  
      # version of Minecraft-- check PaperMC plugin for compatibility
      VERSION: "1.20.6" 

      # gameplay settings
      DIFFICULTY: "normal"
      MODE: "creative" # "survival"
      SERVER_NAME: "PynCraft"
      ALLOW_CHEATS: "true"
      SEED: "9064150133272194"
      # assign admin privileges to particular players (comma-separated)
      OPS: "${OPS_PLAYERS}" 

      # automatically download and install the Geyser and Floodgate plugins
      # these enables players to join the server using Bedrock Edition
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot

      # RCON settings - these allow you to send commands to the server
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: "25575"

    volumes:
      # attach the subdirectory 'data' to the container's /data path
      # format is host_path:container_path (container path should not change)
      - ./data:/data
      # attach a plugins subdirectory to load the FruitJuice plugin
      - ./plugins:/plugins

      